#!/bin/sh

STAGED_REACT_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep -E "(^React)(.src)(.*)(.js$|.jsx$|.ts$|.tsx$)")

if [[ "$STAGED_REACT_FILES" = "" ]]; then
  exit 0
fi

# Check for eslint
which eslint &> /dev/null
if [[ "$?" == 1 ]]; then
  echo "Please install ESlint CLI"
  echo "npm i -g eslint-cli"
  exit 1
fi

REACT_ERRORS=()
# Check React files
cd React
for FILE in $STAGED_REACT_FILES
do
  LINT_RESULT=$(eslint "${FILE/React\//}")
  LINT_RESULT_LENGTH=${#LINT_RESULT}
  if [[ $LINT_RESULT_LENGTH > 0 ]]; then
    REACT_ERRORS+=("$LINT_RESULT")
  fi
done

NUMBER_OF_REACT_ERRORS=${#REACT_ERRORS[@]}
if [[ $NUMBER_OF_REACT_ERRORS > 0 ]]; then
  # Print errors
  echo "COMMIT FAILED"
  echo "Your commit contains files that should pass ESLint but do not. Please fix the ESLint errors and try again."
  echo "Run \"npm run lint:check\" to view all warnings and errors."
  for ERROR in "${REACT_ERRORS[*]}"
  do
    echo "$ERROR"
    echo ""
  done
  exit 1
else
  echo "COMMIT SUCCEEDED"
fi

exit $?