pr:
  branches:
    include:
      - main

trigger: none

pool:
  vmImage: ubuntu-latest

jobs:


- job: 'Build_Functions_App'
  steps:
  - task: NodeTool@0
    displayName: 'Set Node Version'
    inputs:
      versionSource: 'spec'
      versionSpec: '22.x'
      checkLatest: true

  - task: Npm@1
    displayName: 'Install dependencies'
    inputs:
      command: 'install'
      workingDir: 'Azure Functions'

  - task: Npm@1
    displayName: 'Build the app'
    inputs:
      command: 'custom'
      workingDir: 'Azure Functions'
      customCommand: 'build:production'
