pr:
  branches:
    include:
      - main

trigger: none

pool:
  vmImage: ubuntu-latest

jobs:
- job: 'React_CI'
  steps:
  - task: NodeTool@0
    displayName: 'Set Node Version'
    inputs:
      versionSource: 'spec'
      versionSpec: '22.x'
      checkLatest: true

  - task: Npm@1
    displayName: 'Npm install'
    inputs:
      command: 'install'
      workingDir: 'React'

  - task: Npm@1
    displayName: 'Npm run build'
    inputs:
      command: 'custom'
      workingDir: 'React'
      customCommand: 'run build'
